### ISSUE TITLE
Blocked users can not be reactivated in backend

### ISSUE THREAD

**Issue by Benjamin-K** [aertmann/brute-force#2]
When a user is blocked / has expired there is no way to remove the expiration date of that user from within the backend. The only way to achieve this is to update the database directly. There should be an option to set / remove the expiration date in the backend.

**Comment by kaystrobach** [comment]
@Benjamin-K are you using neos or a plain flow application?

**Comment by aertmann** [comment]
Hey sorry didn't get notified of this, so first seeing it now. Adding a way to unblock in the backend would be nice, also being able to see if an account is expired would be useful in general.

I'd actually suggest to add such a feature in the Neos core.
